package factory;

public enum TipoFila {
    FILA_SEQUENCIAL,
    FILA_SIMPLESMENTE_ENCADEADA,
    FILA_CIRCULAR_SIMPLESMENTE_ENCADEADA,
    FILA_CIRCULAR_DUPLAMENTE_ENCADEADA,
    FILA_DE_PRIORIDADE,
    FILA_DE_PRIORIDADE_CIRCULAR,
    FILA_DE_PRIORIDADE_CIRCULAR_DUPLAMENTE_ENCADEADA,
}
